# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('use_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'get_latest_by': 'pub_date',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('body_html', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name=b'Date published')),
                ('enable_comments', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, b'Draft'), (1, b'Published')], default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory')),
            ],
            options={
                'get_latest_by': 'pub_date',
                'verbose_name_plural': 'entries',
            },
        ),
    ]
