# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('pub_date', models.DateTimeField(null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('guid', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('url', models.URLField(help_text=b'URL of an RSS feed or API endpoint')),
                ('last_check', models.DateTimeField(blank=True, editable=False, help_text=b'Most recent HTTP request attempt', null=True)),
                ('last_update', models.DateTimeField(blank=True, editable=False, help_text=b'Date of the most recent item', null=True)),
                ('image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('profile', models.URLField(blank=True, help_text=b'User profile URL, if applicable')),
                ('website', models.URLField(blank=True, help_text=b'URL of the site. Just the domain (and sub-domain), nothing else.')),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, help_text=b'For URLs that require basic HTTP authentication', max_length=255)),
                ('password', models.CharField(blank=True, help_text=b'For URLs that require basic HTTP authentication', max_length=255)),
                ('item_summary_template', models.TextField(blank=True, help_text=b"\n                A custom template for the 'header' display of items of this source on the root page.<br />\n                e.g. '3 scrobbles via Last.FM'<br/>\n                template variables available are: {{ source }} and {{ items }}\n            ")),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifestream.Source'),
        ),
    ]
