# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
